#
#spring:
#    application:
#        name: eureka-provider
#server:
#    port: 10011
#
#eureka:
#   client:
#    serviceUrl:
#        defaultZone:http://localhost:10010/eureka/
#

#spring.application.name=eureka-provider
#
#server.port=10011
#
#eureka.client.serviceUrl.defaultZone=http://localhost:10010/eureka/

spring:
  profiles:
    active: dev
  application:
    name: consul-server
  cloud:
    consul:
      host: localhost
      port: 8500
      config:
        enabled: true
        format: yaml
        data-key: data
        prefix: config
        default-context: consul-provider
        profile-separator: ','

server:
  port: 10013

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"