
spring:
    application:
        name: consul-consumer-feign
    cloud:
      consul:
        host: localhost
        port:8500
server:
    port: 10014

feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        exclude: "*"

#spring.application.name=eureka-consumer-feign
#
#server.port=10012
#
#eureka.client.serviceUrl.defaultZone=http://localhost:10010/eureka/

