#spring.application.name=eureka-server
#
#server.port=10010
#
#eureka.instance.hostname=localhost    设置eureka 所在服务器中的主机名称

#eureka.client.register-with-eureka=false
#eureka.client.fetch-registry=false    表示是否从Eureka Server获取注册信息，默认为true。
#                                      自测的时候是一个单点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设置为false。

spring:
    application:
        name: eureka-server
server:
    port: 10010

eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: false
        fetch-registry: false